site_name: Jampamane
site_description: The offical personal / professional website for Jeremy Brandow
site_url: https://www.jampamane.org
repo_url: https://github.com/Jampamane/website
repo_name: Jampamane/website

theme:
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  logo: assets/profile_pic.jpg
  favicon: assets/profile_pic.jpg
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.path
  palette:
    - primary: black
      accent: orange
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - primary: black
      accent: orange
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - admonition
  - attr_list
  - def_list
  - md_in_html


plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: Jampamane/website
      branch: main
  - blog:
      enabled: true
      categories: true
      post_excerpt: required
      pagination: true
      pagination_per_page: 5
      authors: true
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  # - git-committers:
  #     repository: Jampamane/website
  #     branch: main

extra_css:
  - styles/homepage.css

extra_javascript:
  - javascripts/scroll.js
  - javascripts/smooth_homepage_image.js
  - javascripts/giscus_theme.js

nav:
  - Home: index.md
  # - Resume: resume/index.md
  # - Projects:
  #   - projects/index.md
  # - Youtube:
  #   - youtube/index.md
  - Blog:
    - blog/index.md
