authors:
  jampamane:
    name: Jeremy Brandow
    description: Creator
    avatar: https://raw.githubusercontent.com/Jampamane/website/refs/heads/main/docs/assets/profile_pic.jpg
    url: https://github.com/Jampamane